// AUTO-GENERATED by WaratahCmd.exe

#include <memory>

// HID Usage Tables: 1.3.0
// Descriptor size: 140 (bytes)
// +----------+--------+------------------+
// | ReportId | Kind   | ReportSizeInBits |
// +----------+--------+------------------+
// |        1 | Input  |              104 |
// +----------+--------+------------------+
// |        1 | Output |                8 |
// +----------+--------+------------------+
// |        2 | Input  |               96 |
// +----------+--------+------------------+
static const uint8_t reportDescriptor [] = 
{
    0x05, 0x01,          // UsagePage(Generic Desktop[1])
    0x09, 0x06,          // UsageId(Keyboard[6])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x01,          //     ReportId(1)
    0x05, 0x07,          //     UsagePage(Keyboard/Keypad[7])
    0x19, 0xE0,          //     UsageIdMin(Keyboard LeftControl[224])
    0x29, 0xE7,          //     UsageIdMax(Keyboard Right GUI[231])
    0x15, 0x00,          //     LogicalMinimum(0)
    0x25, 0x01,          //     LogicalMaximum(1)
    0x95, 0x08,          //     ReportCount(8)
    0x75, 0x01,          //     ReportSize(1)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x19, 0x04,          //     UsageIdMin(Keyboard A[4])
    0x29, 0x63,          //     UsageIdMax(Keypad Period[99])
    0x95, 0x60,          //     ReportCount(96)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x08,          //     UsagePage(LED[8])
    0x19, 0x01,          //     UsageIdMin(Num Lock[1])
    0x29, 0x05,          //     UsageIdMax(Kana[5])
    0x95, 0x05,          //     ReportCount(5)
    0x91, 0x02,          //     Output(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x95, 0x01,          //     ReportCount(1)
    0x75, 0x03,          //     ReportSize(3)
    0x91, 0x03,          //     Output(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0xC0,                // EndCollection()
    0x05, 0x01,          // UsagePage(Generic Desktop[1])
    0x09, 0x05,          // UsageId(Gamepad[5])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x02,          //     ReportId(2)
    0x09, 0x30,          //     UsageId(X[48])
    0x15, 0x81,          //     LogicalMinimum(-127)
    0x25, 0x7F,          //     LogicalMaximum(127)
    0x75, 0x08,          //     ReportSize(8)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x31,          //     UsageId(Y[49])
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x32,          //     UsageId(Z[50])
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x35,          //     UsageId(Rz[53])
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x33,          //     UsageId(Rx[51])
    0x15, 0x00,          //     LogicalMinimum(0)
    0x26, 0xFF, 0x00,    //     LogicalMaximum(255)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x34,          //     UsageId(Ry[52])
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x39,          //     UsageId(Hat Switch[57])
    0x46, 0x3B, 0x01,    //     PhysicalMaximum(315)
    0x15, 0x01,          //     LogicalMinimum(1)
    0x25, 0x08,          //     LogicalMaximum(8)
    0x75, 0x04,          //     ReportSize(4)
    0x81, 0x42,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NullState, BitField)
    0x81, 0x03,          //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x3D,          //     UsageId(Start[61])
    0x45, 0x00,          //     PhysicalMaximum(0)
    0x15, 0x00,          //     LogicalMinimum(0)
    0x25, 0x01,          //     LogicalMaximum(1)
    0x75, 0x01,          //     ReportSize(1)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x3E,          //     UsageId(Select[62])
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x75, 0x06,          //     ReportSize(6)
    0x81, 0x03,          //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x09,          //     UsagePage(Button[9])
    0x19, 0x01,          //     UsageIdMin(Button 1[1])
    0x29, 0x20,          //     UsageIdMax(Button 32[32])
    0x95, 0x20,          //     ReportCount(32)
    0x75, 0x01,          //     ReportSize(1)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                // EndCollection()
};